apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: ai-demo
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      name: frontend
      labels:
        app: frontend
    spec:
      containers:
        - args:
            - streamlit
            - run
            - HOME.py
          env:
            - name: STABLE_V1_IP
              value: stablev1-service
          name: frontend
          image: amineschercloud/frontend
          ports:
            - containerPort: 8501
            - containerPort: 9000
          resources: {}
      restartPolicy: Always
status: {}

---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: ai-demo
spec:
  selector:
    app: frontend
  ports:
    - name: "8501"
      port: 8501
      targetPort: 8501
  type: ClusterIP
